run_location: ./scripts
webserver:
  port: 8080
  enabletls: false
  tlscert: ''
  tlskey: ''
  general_token: smGBs3pcXJokB1tt7Psq5X1hA4CqWNEw

hooks:
  - name: example-hook
    enabled: true
    endpoint: /test
    methods:
      - GET
    scripts:
      - bash ./example.sh
    token: ''
