webserver:
  port: 8080
  enabletls: false
  tlscert: ''
  tlskey: ''
  general_token: F4rBKuCWY1y2_M0jZ2IJFcoVlp3MfDKW
  
hooks:
  - name: example-hook
    enabled: true
    endpoint: '/test/:name'
    methods:
      - GET
      - POST
    scripts:
      - bash ./scripts/example.sh
    token: 'abc'
